### PR TITLE
17th congress

### PR DESCRIPTION
**Pull request by jfbratt**
Does not have the 16th congress data. That was merged after I branched.

### CODE REVIEW

**Comment by lmullen** [comment]
@jfbratt: I’m seeing some of the merge conflict indicators in the file, eg lines 9676 and 10595 ff. in the candidate totals data. Could you please check for those in all files?

**Comment by lmullen** [comment]
Why is the diff showing more deletions than additions?

**Comment by jfbratt** [comment]
The congressional-candidates-totals.csv had multiple iterations of the data (3 iterations). From what I read on merge tutorials, it was showing me the various versions of the file. I just didn't clean/choose the correct version. So I removed the other iterations. I don't know if I am explaining this well.

**Comment by jfbratt** [comment]
You can see that it was tripled in commit 7a70463

**Comment by lmullen** [comment]
So we are good to merge in your opinion?

**Comment by jfbratt** [comment]
It looks good to me. I will have to take some more time to go over merge tutorials.

**Comment by lmullen** [comment]
Okay this is merged in. Thanks for working on it. You can base the 18th Congress branch on master.

**Pull request merged**
