### PR TITLE
Add Data From 12th Congress

### PR DESCRIPTION
**Pull request by DanielKim1**

### CODE REVIEW

**Comment by lmullen** [comment]
@DanielKim1 This pull request has a merge conflict. I'm guessing it has to do with updated data on master between the time when you created this branch. Could you please update this branch and resolve the conflict?

**Comment by DanielKim1** [comment]
@lmullen I finally figured out how to use mergetool, the pull request is good to go

**Comment by lmullen** [comment]
@DanielKim1 Brilliant. Do you have a sense of what went wrong with the merge initially?

**Comment by DanielKim1** [comment]
The conflict came from the congress 11 data and the congress 12 data simultaneously being appended to the congress 1-10 data.

When I was adding data from congresses 11-13, I should have done the this:
1. make new branch from master, add congress 11
2. make new branch from sum(master, 11), add congress 12
3. make new branch from sum(master, 11, 12), add congress 13

Instead, I did the following:
1. make new branch from master, add congress 11
2. make new branch from master, add congress 12
3. make new branch from master, add congress 13

**Pull request merged**
